### ISSUE TITLE
Website - update F-Droid information

### ISSUE THREAD

**Issue by licaon-kter** [futo-org/circles-android#4]
### Steps to reproduce

https://circu.li/index.html has no F-Droid mention just Play

https://circu.li/circles.html has an F-Droid logo that links to the upstream repo

### Additional info

https://circu.li/ should have an F-Droid logo

Buuuut, that should link to a page that has 2 sections

One for upstream repo, that's called "our repo" or something

Second for F-Droid itself, say a link using the "Get it on F-Droid" logo

eg. https://cryptomator.org/android/

or https://simplex.chat/fdroid/

### Application version

-

### App Store name

F-Droid

**Comment by cvwright** [comment]
A new website is coming in the next week or two.  We will definitely include a link to the app on F-Droid.org !

**Comment by licaon-kter** [comment]
https://circu.li/fdroid/repo/ -> 404

**Comment by TarasSmakula** [comment]
new website https://circles.futo.org/

**Comment by licaon-kter** [comment]
@TarasSmakula fix link, should be `https://f-droid.org/packages/org.futo.circles/`

**Comment by cvwright** [comment]
Thanks @licaon-kter - the link has been fixed
