### ISSUE TITLE
Privacy policy invalid URL on eu.circles.futo.org server

### ISSUE THREAD

**Issue by Divinelink** [futo-org/circles-android#9]
### Steps to reproduce

1. Sign Up
2. Select "eu.circles.futo.org" server
3. Tap on Privacy Policy link 

### Additional info

It appears that the URL for privacy policy is invalid, only for "eu.circles.futo.org" server. By clicking the privacy link, I'm getting re-directed to `https://circles.futo.org/privacy/service.html` while the URL for "circles.futo.org" server is `https://circles.futo.org/privacy/service/index.html` and works correctly.

### Screen recording
https://github.com/futo-org/circles-android/assets/25794786/6605a250-e319-4562-aa87-c84584fca67b

### Application version

v1.0.30

### App Store name

Google Play Store

### Phone model

Samsung S23+

### Operating system version

Android 14

**Comment by TarasSmakula** [comment]
Fixed. Thanks
